version: '3.8'

services: 
  mysqldb:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    env_file: ./.env
    environment:
      MYSQL_HOST_IP: localhost
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
  app:
    build:
        context: .
        dockerfile: ./Dockerfile
    image: node-mysql-app
    depends_on:
        - mysqldb
    links:
      - mysqldb
    stdin_open : true
    tty: true


volumes: 
  db-config:
  db-data:
