version: '3.8'

services: 
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: localhost
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: filedb
    ports:
      - 3307:3306
    container_name: gaspardloriot
  app:
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: mydb
    image: node-mysql-app
    depends_on:
        - mysqldb
    links:
      - mysqldb
    stdin_open : true
    tty: true

